### ISSUE TITLE
Inconsistency in date of confirmation causes noisy/spiky UK 7d average plot

### ISSUE THREAD

**Issue by corneliusroemer** [globaldothealth/monkeypox#161]
England has released new case data twice weekly for a while now - always on Tuesday and Friday.

As their publishing schedule is quite regular, I was surprised to find the 7d average case rate plot for the UK to be so spiky:
<img width="1929" alt="image" src="https://user-images.githubusercontent.com/25161793/183738770-cb34c8c1-2217-418e-aa30-7dfbcc9f202c.png">

When I investigated the date of confirmation for the English cases in your Google Sheet, I noticed what causes the spikes:
you seem to be inconsistent on the weekdays these English cases get attributed. 

Could you double check that you choose consistent weekdays for date of confirmation? That way Spikes in the 7d average plots would disappear.

Thanks a lot!

Here's the pivot table I used to spot the issue:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/25161793/183739620-f32ce3bb-fb19-4b2c-b0f2-5dbe7be8ef05.png">

These are the official dates of the update, you should probably align with these dates:
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/25161793/183739874-f4d5d34e-469a-431b-bfd7-0e00975b0264.png">
See https://www.gov.uk/government/news/monkeypox-cases-confirmed-in-england-latest-updates#full-publication-update-history

You mostly seem to have chosen cutoff date used by UKHSA - but sometimes you used report day. It should be easy to fix - just filter to English cases and do some bulk editing. Thanks!

**Comment by tvarrelman** [comment]
Hi @corneliusroemer , thank you for finding this issue and providing a detailed report. I can confirm that the G.h cases derived from the 2022-07-19, 2022-07-15, and 2022-06-24 Epidemiological Overviews had a Date_confirmation of the publication date instead of the cutoff described by the UKHSA. I have resolved this issue. 

As for the Date_confirmation of 2022-06-26, this was the cutoff date described by the UKHSA in the following report:
https://www.gov.uk/government/publications/monkeypox-outbreak-epidemiological-overview/monkeypox-outbreak-epidemiological-overview-28-june-2022.

Thanks!

**Comment by corneliusroemer** [comment]
Excellent, thanks @tvarrelman!

There may be similar issues in other countries' data - would be great to check this systematically. You probably have a list of websites for each country that you check this in.
