### ISSUE TITLE
Confirmation dates missing IDs 1841 and 1842

### ISSUE THREAD

**Issue by vi-enne** [globaldothealth/monkeypox#86]
![image](https://user-images.githubusercontent.com/44818674/173414273-7423143e-1b7e-4f3a-bc33-9522beae2c5f.png)

**Comment by vi-enne** [comment]
I would suggest to implement the check also for Age (verify it is a numeric interval) and Gender (verify it is a lowercase string).

**Comment by TKrepo** [comment]
I have an automatic validation running on a local Excel-Sheet that creates dynamically a table with the missing dates.

You could do this on your Google Sheet. Simply create a column (here A) filled with this formula:

=INDEX(ID; MATCH(0; COUNTIF($A$1:$A1; ID) + (STATUS <> "confirmed") + ISNUMBER(CDATE); 0))

where ID, STATUS, and CDATE are named Ranges for your corresponding columns. Maybe you have to change the ISNUMBER part, because I replace empty fields with a "" when importing your data.

**Comment by abhidg** [comment]
@vi-enne there are age and gender checks in src/qc.py. @ksewalk I have added a check for missing confirmation date in 50fcebfed33ecaf8e2e5a060db2c36d6c684ee51
